// 全ジャンル共通のデザイン知識（スタイル・配色・書体・モーション・効果音・業種）
// ここを編集して `npm run build:db` すると全DBが再生成されます。

/** スタイル（トーン&マナー）。各スタイルに配色・書体・モーション・音・グラフィックの「相性の良い組み合わせ」を定義 */
export const STYLES = [
  {
    id: 'minimal', name: 'ミニマル・洗練', keywords: ['シンプル', '余白', '上品', 'モノトーン', 'クリーン'],
    palettes: [
      { name: 'Paper White', bg: '#FAFAF7', surface: '#EFEEE9', text: '#1A1A1A', primary: '#1A1A1A', accent: '#C8553D' },
      { name: 'Stone', bg: '#F3F1EC', surface: '#E4E0D7', text: '#2B2A27', primary: '#3E5641', accent: '#B08D57' },
      { name: 'Ink Blue', bg: '#FFFFFF', surface: '#F2F4F7', text: '#0E1525', primary: '#1D3557', accent: '#E76F51' },
      { name: 'Fog', bg: '#F5F6F6', surface: '#E8EAEA', text: '#202424', primary: '#4A5859', accent: '#D4A373' },
    ],
    fonts: [
      { head: 'Zen Kaku Gothic New', body: 'Noto Sans JP', en: 'Inter' },
      { head: 'Noto Serif JP', body: 'Noto Sans JP', en: 'Cormorant Garamond' },
      { head: 'BIZ UDPGothic', body: 'Noto Sans JP', en: 'Manrope' },
    ],
    motions: ['fade-up', 'clip-up', 'split-text', 'line-draw', 'parallax', 'mask-wipe'],
    sfx: ['tick', 'soft-bell', 'page-turn'],
    graphics: ['細い罫線', '大きな余白', '小さな英字キャプション', 'モノクロ写真', '縦書きアクセント'],
    gfx: ['rings', null],
  },
  {
    id: 'luxury', name: 'ラグジュアリー・高級感', keywords: ['高級', 'ゴールド', '黒', 'エレガント', '上質'],
    palettes: [
      { name: 'Noir Gold', bg: '#0E0E0E', surface: '#1A1918', text: '#EDE8DF', primary: '#C9A96E', accent: '#E8D3A8' },
      { name: 'Champagne', bg: '#F7F2EA', surface: '#ECE3D3', text: '#2A2420', primary: '#8C6A43', accent: '#B8935A' },
      { name: 'Emerald Night', bg: '#0B1F1A', surface: '#12302A', text: '#EFE9DC', primary: '#C5A572', accent: '#7FB7A4' },
      { name: 'Bordeaux', bg: '#1B0D10', surface: '#2B1418', text: '#F3E9E2', primary: '#B89262', accent: '#8E2C3A' },
    ],
    fonts: [
      { head: 'Shippori Mincho', body: 'Noto Serif JP', en: 'Cormorant Garamond' },
      { head: 'Zen Old Mincho', body: 'Noto Sans JP', en: 'Playfair Display' },
      { head: 'Noto Serif JP', body: 'Noto Sans JP', en: 'Cinzel' },
    ],
    motions: ['blur-in', 'clip-up', 'split-text', 'ken-burns', 'shine-sweep', 'mask-wipe', 'cursor-follow'],
    sfx: ['soft-bell', 'chime', 'sparkle'],
    graphics: ['金の細線フレーム', 'セリフ体の大文字英字', 'ゴールドの光沢グラデ', '大判の陰影写真', 'ダイヤ型の装飾'],
    gfx: ['bokeh', 'particles'],
  },
  {
    id: 'natural', name: 'ナチュラル・オーガニック', keywords: ['自然', '優しい', 'ベージュ', '植物', '手作り感'],
    palettes: [
      { name: 'Sage', bg: '#F6F4EE', surface: '#E7E9DD', text: '#2F3A2F', primary: '#6B8F71', accent: '#D99A6C' },
      { name: 'Linen', bg: '#FBF8F3', surface: '#F0E8DC', text: '#3B3127', primary: '#A47551', accent: '#7C9473' },
      { name: 'Matcha Latte', bg: '#F4F1E8', surface: '#E3E6D3', text: '#33362B', primary: '#7D8F4E', accent: '#C78B5E' },
      { name: 'Terracotta', bg: '#FAF5EF', surface: '#F1E2D3', text: '#3D2B22', primary: '#C0714F', accent: '#5E7D63' },
    ],
    fonts: [
      { head: 'Zen Maru Gothic', body: 'Noto Sans JP', en: 'Quicksand' },
      { head: 'Klee One', body: 'Zen Kaku Gothic New', en: 'Lora' },
      { head: 'Kiwi Maru', body: 'Noto Sans JP', en: 'Nunito' },
    ],
    motions: ['fade-up', 'float', 'blob-morph', 'wave', 'parallax', 'line-draw'],
    sfx: ['bubble', 'soft-bell', 'drop'],
    graphics: ['手書き風の線画', '葉っぱのシルエット', 'クラフト紙テクスチャ', '有機的なブロブ形状', '丸みのある角'],
    gfx: ['waves', 'sakura'],
  },
  {
    id: 'pop', name: 'ポップ・カラフル', keywords: ['元気', '明るい', '楽しい', 'ビビッド', '若年層'],
    palettes: [
      { name: 'Candy', bg: '#FFF8E7', surface: '#FFE3EC', text: '#1F1A3D', primary: '#FF4F81', accent: '#2EC4B6' },
      { name: 'Sunny', bg: '#FFFBEA', surface: '#FFF0B3', text: '#1D1D1D', primary: '#FF6B00', accent: '#3A86FF' },
      { name: 'Lemon Soda', bg: '#F2FFF9', surface: '#D9FBEA', text: '#14213D', primary: '#06D6A0', accent: '#FFD60A' },
      { name: 'Grape', bg: '#F7F1FF', surface: '#E9DCFF', text: '#20123A', primary: '#7B2FF7', accent: '#FFB703' },
    ],
    fonts: [
      { head: 'M PLUS Rounded 1c', body: 'M PLUS Rounded 1c', en: 'Poppins' },
      { head: 'Dela Gothic One', body: 'Noto Sans JP', en: 'Rubik' },
      { head: 'RocknRoll One', body: 'Zen Maru Gothic', en: 'Fredoka' },
    ],
    motions: ['pop', 'bounce', 'wiggle', 'marquee', 'confetti', 'split-text', 'tilt-3d'],
    sfx: ['pop', 'bubble', 'coin', 'confetti'],
    graphics: ['太い縁取り文字', '吹き出し', 'ステッカー風パーツ', 'ドット柄', '斜めストライプ帯'],
    gfx: ['particles', 'mesh'],
  },
  {
    id: 'tech', name: 'クール・テック', keywords: ['先進的', 'AI', 'SaaS', 'ダーク', 'グロー'],
    palettes: [
      { name: 'Midnight Indigo', bg: '#0A0E1A', surface: '#121A2E', text: '#E6EAF5', primary: '#5B8CFF', accent: '#33E1C2' },
      { name: 'Electric', bg: '#06070D', surface: '#11131F', text: '#F1F3FA', primary: '#7C5CFF', accent: '#00D1FF' },
      { name: 'Clean SaaS', bg: '#FFFFFF', surface: '#F4F6FB', text: '#0F172A', primary: '#2563EB', accent: '#14B8A6' },
      { name: 'Aurora', bg: '#070B14', surface: '#0F1726', text: '#EAF2FF', primary: '#22D3EE', accent: '#A78BFA' },
    ],
    fonts: [
      { head: 'Noto Sans JP', body: 'Noto Sans JP', en: 'Space Grotesk' },
      { head: 'IBM Plex Sans JP', body: 'IBM Plex Sans JP', en: 'IBM Plex Mono' },
      { head: 'Zen Kaku Gothic New', body: 'Noto Sans JP', en: 'Sora' },
    ],
    motions: ['constellation', 'gradient-shift', 'typewriter', 'counter-up', 'glow-border', 'tilt-3d', 'scroll-progress'],
    sfx: ['click', 'tick', 'notify', 'unlock'],
    graphics: ['グロー（発光）', 'グリッド線背景', 'コード片', 'グラデーションの境界線', 'UIモック画面'],
    gfx: ['constellation', 'mesh'],
  },
  {
    id: 'wamodern', name: '和モダン', keywords: ['和', '伝統', '旅館', '和菓子', '筆文字'],
    palettes: [
      { name: '藍と生成り', bg: '#F5F0E6', surface: '#E8DFCF', text: '#1E2A3A', primary: '#264653', accent: '#B5463C' },
      { name: '墨と朱', bg: '#F7F3EC', surface: '#EAE3D6', text: '#1B1B1B', primary: '#1B1B1B', accent: '#C0392B' },
      { name: '抹茶と金', bg: '#F2EFE4', surface: '#DFE0CC', text: '#2C2E22', primary: '#4F6F52', accent: '#B8963E' },
      { name: '夜桜', bg: '#14111A', surface: '#221C2B', text: '#F2EAF0', primary: '#E8A0BF', accent: '#C9A96E' },
    ],
    fonts: [
      { head: 'Shippori Mincho B1', body: 'Noto Serif JP', en: 'Cormorant Garamond' },
      { head: 'Zen Antique', body: 'Noto Sans JP', en: 'EB Garamond' },
      { head: 'Yuji Syuku', body: 'Noto Serif JP', en: 'Cormorant' },
    ],
    motions: ['clip-up', 'vertical-text-reveal', 'ink-spread', 'sakura', 'parallax', 'blur-in'],
    sfx: ['koto', 'soft-bell', 'page-turn'],
    graphics: ['縦書き', '和柄（青海波・麻の葉）', '落款風の判子', '余白と墨の滲み', '障子・格子のグリッド'],
    gfx: ['sakura', 'rings'],
  },
  {
    id: 'retro', name: 'レトロ・Y2K', keywords: ['懐かしい', '昭和レトロ', '平成', 'Y2K', 'ノスタルジー'],
    palettes: [
      { name: 'Showa Cafe', bg: '#F4E9D8', surface: '#E9D5B5', text: '#3B2416', primary: '#C8553D', accent: '#2A9D8F' },
      { name: 'Y2K Chrome', bg: '#EDEBFF', surface: '#D9E4FF', text: '#140F3A', primary: '#FF4FD8', accent: '#3DDCFF' },
      { name: 'Synthwave', bg: '#1A0B2E', surface: '#2B1250', text: '#FCE7FF', primary: '#FF2975', accent: '#FFD319' },
      { name: 'Retro Diner', bg: '#FFF3E0', surface: '#FFE0B2', text: '#2B1B12', primary: '#E63946', accent: '#1D7874' },
    ],
    fonts: [
      { head: 'Rampart One', body: 'M PLUS 1p', en: 'Bungee' },
      { head: 'DotGothic16', body: 'M PLUS 1p', en: 'Press Start 2P' },
      { head: 'Mochiy Pop One', body: 'Zen Maru Gothic', en: 'Righteous' },
    ],
    motions: ['glitch', 'marquee', 'grid3d', 'chrome-shine', 'bounce', 'typewriter'],
    sfx: ['coin', 'level-up', 'glitch', 'jingle'],
    graphics: ['クローム文字', 'ハーフトーン', 'ドット絵', '昭和フォントの看板', 'ギザギザの吹き出し'],
    gfx: ['grid3d', 'particles'],
  },
  {
    id: 'editorial', name: 'エディトリアル・雑誌風', keywords: ['雑誌', 'おしゃれ', 'ファッション', 'タイポ', '大胆'],
    palettes: [
      { name: 'Magazine', bg: '#F6F3EE', surface: '#E9E4DA', text: '#141414', primary: '#141414', accent: '#E4572E' },
      { name: 'Vogue Red', bg: '#FFFFFF', surface: '#F1EFEA', text: '#111111', primary: '#D7263D', accent: '#111111' },
      { name: 'Olive Press', bg: '#EEEDE6', surface: '#DEDDD2', text: '#1D1F17', primary: '#545B2E', accent: '#E0A458' },
      { name: 'Cobalt Print', bg: '#F4F1EA', surface: '#E5E0D4', text: '#101820', primary: '#1E3FAE', accent: '#F2A900' },
    ],
    fonts: [
      { head: 'Noto Serif JP', body: 'Noto Sans JP', en: 'Playfair Display' },
      { head: 'Zen Old Mincho', body: 'Zen Kaku Gothic New', en: 'DM Serif Display' },
      { head: 'Shippori Mincho', body: 'Noto Sans JP', en: 'Bodoni Moda' },
    ],
    motions: ['split-text', 'clip-left', 'horizontal-scroll', 'image-hover-zoom', 'marquee', 'cursor-follow'],
    sfx: ['page-turn', 'shutter', 'tick'],
    graphics: ['超大型の英字見出し', '写真と文字の重なり', '段組み', 'ナンバリング（01/02/03）', '縦の細いキャプション'],
    gfx: [null],
  },
  {
    id: 'cute', name: 'かわいい・ガーリー', keywords: ['かわいい', 'ピンク', '女性向け', 'ふんわり', '癒し'],
    palettes: [
      { name: 'Peach Milk', bg: '#FFF6F2', surface: '#FFE4DC', text: '#4A2E35', primary: '#F48FB1', accent: '#FFB4A2' },
      { name: 'Lavender', bg: '#FAF7FF', surface: '#ECE4FF', text: '#3A2D52', primary: '#B39DDB', accent: '#F8BBD0' },
      { name: 'Mint Cream', bg: '#F5FFFB', surface: '#DDF6EC', text: '#2E4A44', primary: '#7FD1B9', accent: '#FFAFCC' },
      { name: 'Strawberry', bg: '#FFF5F7', surface: '#FFDDE5', text: '#4B1D2B', primary: '#EF476F', accent: '#FFD166' },
    ],
    fonts: [
      { head: 'Zen Maru Gothic', body: 'Zen Maru Gothic', en: 'Quicksand' },
      { head: 'Hachi Maru Pop', body: 'M PLUS Rounded 1c', en: 'Pacifico' },
      { head: 'Kosugi Maru', body: 'Noto Sans JP', en: 'Comfortaa' },
    ],
    motions: ['float', 'pop', 'sparkle', 'blob-morph', 'bounce', 'heart-burst'],
    sfx: ['sparkle', 'bubble', 'pop', 'soft-bell'],
    graphics: ['リボン', 'キラキラ', 'ハート', '丸い写真フレーム', '手書きの吹き出し'],
    gfx: ['bokeh', 'sakura'],
  },
  {
    id: 'trust', name: '信頼・誠実（コーポレート）', keywords: ['信頼', '安心', '企業', '誠実', 'ブルー'],
    palettes: [
      { name: 'Corporate Navy', bg: '#FFFFFF', surface: '#F2F5F9', text: '#13223A', primary: '#0B3C7A', accent: '#F0A202' },
      { name: 'Medical Teal', bg: '#FFFFFF', surface: '#EEF7F7', text: '#16302F', primary: '#0F7C80', accent: '#F28C38' },
      { name: 'Finance Green', bg: '#FCFDFC', surface: '#EEF4EF', text: '#162A1E', primary: '#1F6E43', accent: '#D4A017' },
      { name: 'Sky', bg: '#F8FBFF', surface: '#E8F1FB', text: '#122033', primary: '#1E6FD9', accent: '#FF7A45' },
    ],
    fonts: [
      { head: 'Noto Sans JP', body: 'Noto Sans JP', en: 'Inter' },
      { head: 'BIZ UDPGothic', body: 'BIZ UDPGothic', en: 'Source Sans 3' },
      { head: 'Zen Kaku Gothic New', body: 'Noto Sans JP', en: 'Montserrat' },
    ],
    motions: ['fade-up', 'counter-up', 'stagger', 'line-draw', 'parallax', 'scroll-progress'],
    sfx: ['tick', 'success', 'notify'],
    graphics: ['実績数字の大表示', '人物写真（笑顔・正面）', 'アイコン付き3カラム', '認証バッジ', '斜めの背景帯'],
    gfx: ['waves', 'rings'],
  },
  {
    id: 'sporty', name: 'エネルギッシュ・スポーティ', keywords: ['力強い', '情熱', 'スピード感', '筋トレ', 'イエロー'],
    palettes: [
      { name: 'Volt', bg: '#0D0D0D', surface: '#1C1C1C', text: '#FFFFFF', primary: '#D7FF00', accent: '#FF3B30' },
      { name: 'Fire', bg: '#FFFFFF', surface: '#F3F3F3', text: '#111111', primary: '#FF3B1F', accent: '#111111' },
      { name: 'Racing', bg: '#0B132B', surface: '#1C2541', text: '#FFFFFF', primary: '#FF9F1C', accent: '#2EC4B6' },
      { name: 'Court', bg: '#F5F7F2', surface: '#E3EADB', text: '#101810', primary: '#00A86B', accent: '#FFCC00' },
    ],
    fonts: [
      { head: 'Dela Gothic One', body: 'Noto Sans JP', en: 'Anton' },
      { head: 'Reggae One', body: 'Noto Sans JP', en: 'Bebas Neue' },
      { head: 'Noto Sans JP', body: 'Noto Sans JP', en: 'Oswald' },
    ],
    motions: ['zoom-in', 'skew-reveal', 'marquee', 'counter-up', 'speed-lines', 'impact-shake'],
    sfx: ['impact', 'whoosh', 'riser', 'swoosh'],
    graphics: ['斜体の極太文字', '集中線・スピード線', '斜めカット写真', 'ナンバー（背番号風）', 'テープ帯'],
    gfx: ['particles', null],
  },
  {
    id: 'cinematic', name: 'ダーク・シネマティック', keywords: ['映画', '没入感', '暗い', 'ドラマチック', '映像'],
    palettes: [
      { name: 'Film Noir', bg: '#08080A', surface: '#141418', text: '#F2F2F2', primary: '#E50914', accent: '#F5C518' },
      { name: 'Teal Orange', bg: '#0A1416', surface: '#13252A', text: '#EDEDED', primary: '#FF8C42', accent: '#2EC4B6' },
      { name: 'Deep Space', bg: '#05060B', surface: '#0F1220', text: '#E8E8F0', primary: '#8E9CFF', accent: '#FF6F91' },
      { name: 'Smoke', bg: '#111111', surface: '#1E1E1E', text: '#E6E1D8', primary: '#D9C5A0', accent: '#8C2F39' },
    ],
    fonts: [
      { head: 'Shippori Mincho', body: 'Noto Sans JP', en: 'Cinzel' },
      { head: 'Noto Sans JP', body: 'Noto Sans JP', en: 'Bebas Neue' },
      { head: 'Zen Old Mincho', body: 'Noto Sans JP', en: 'Cormorant Garamond' },
    ],
    motions: ['ken-burns', 'letterbox-open', 'blur-in', 'split-text', 'grain', 'sticky-scrub'],
    sfx: ['riser', 'impact', 'whoosh', 'heartbeat'],
    graphics: ['シネマスコープの黒帯', 'フィルムグレイン', '逆光写真', '字幕風テキスト', 'ライトリーク'],
    gfx: ['particles', 'bokeh'],
  },
  {
    id: 'glass', name: 'グラスモーフィズム', keywords: ['透明感', 'すりガラス', 'グラデーション', '近未来', 'アプリ'],
    palettes: [
      { name: 'Glass Aurora', bg: '#0F1030', surface: '#1F2160', text: '#FFFFFF', primary: '#8A7BFF', accent: '#FF8FD8' },
      { name: 'Glass Sky', bg: '#DCE9FF', surface: '#FFFFFF', text: '#14213D', primary: '#4361EE', accent: '#F72585' },
      { name: 'Glass Sunset', bg: '#2B0F3A', surface: '#4A1D5C', text: '#FFF5F7', primary: '#FF7E5F', accent: '#FEB47B' },
      { name: 'Glass Mint', bg: '#E6FFF7', surface: '#FFFFFF', text: '#0B2B26', primary: '#00B894', accent: '#6C5CE7' },
    ],
    fonts: [
      { head: 'Noto Sans JP', body: 'Noto Sans JP', en: 'Outfit' },
      { head: 'M PLUS 1p', body: 'Noto Sans JP', en: 'Plus Jakarta Sans' },
      { head: 'Zen Kaku Gothic New', body: 'Noto Sans JP', en: 'Urbanist' },
    ],
    motions: ['mesh', 'tilt-3d', 'float', 'blur-in', 'gradient-shift', 'magnetic'],
    sfx: ['bubble', 'swipe', 'toggle', 'notify'],
    graphics: ['backdrop-filter: blur のカード', '光る境界線', 'ぼかしたカラーオーブ', '半透明レイヤーの重なり', '3Dアイコン'],
    gfx: ['mesh', 'bokeh'],
  },
  {
    id: 'brutal', name: 'ニューブルータリズム', keywords: ['個性的', '太線', '原色', 'アート', '尖った'],
    palettes: [
      { name: 'Brutal Yellow', bg: '#FFE95C', surface: '#FFFFFF', text: '#000000', primary: '#000000', accent: '#FF5C8A' },
      { name: 'Brutal Blue', bg: '#F1F1F1', surface: '#FFFFFF', text: '#000000', primary: '#2B59FF', accent: '#FFDE00' },
      { name: 'Brutal Mint', bg: '#B8F2E6', surface: '#FFFFFF', text: '#000000', primary: '#000000', accent: '#FF6B35' },
      { name: 'Acid', bg: '#E8FF4B', surface: '#FFFFFF', text: '#0A0A0A', primary: '#7A00FF', accent: '#FF2E63' },
    ],
    fonts: [
      { head: 'Dela Gothic One', body: 'M PLUS 1p', en: 'Archivo Black' },
      { head: 'Mochiy Pop One', body: 'Noto Sans JP', en: 'Space Mono' },
      { head: 'Rampart One', body: 'Noto Sans JP', en: 'Syne' },
    ],
    motions: ['hard-shadow-press', 'marquee', 'wiggle', 'pop', 'cursor-follow', 'glitch'],
    sfx: ['click', 'pop', 'coin', 'glitch'],
    graphics: ['3px黒枠', 'ズレた影（ハードシャドウ）', 'ステッカー', '等幅フォント', '手書きの丸囲み'],
    gfx: [null],
  },
  {
    id: 'pastel', name: 'パステル・ドリーミー', keywords: ['ゆめかわ', 'パステル', '淡い', '透明感', 'ふわふわ'],
    palettes: [
      { name: 'Cotton Candy', bg: '#FDF6FF', surface: '#F0E6FF', text: '#3D3359', primary: '#C3A6FF', accent: '#9BE7FF' },
      { name: 'Morning Haze', bg: '#F7FBFF', surface: '#E3F1FF', text: '#2D3A4F', primary: '#8EC5FC', accent: '#E0C3FC' },
      { name: 'Sherbet', bg: '#FFFBF5', surface: '#FFEFD9', text: '#4A3B33', primary: '#FFB5A7', accent: '#B8E0D2' },
      { name: 'Opal', bg: '#F9FAFF', surface: '#EAF0FF', text: '#323A56', primary: '#A0C4FF', accent: '#FFC6FF' },
    ],
    fonts: [
      { head: 'Zen Maru Gothic', body: 'Zen Maru Gothic', en: 'Comfortaa' },
      { head: 'Kaisei Opti', body: 'Noto Sans JP', en: 'Cormorant' },
      { head: 'M PLUS Rounded 1c', body: 'Noto Sans JP', en: 'Nunito' },
    ],
    motions: ['mesh', 'float', 'blur-in', 'sparkle', 'gradient-shift', 'blob-morph'],
    sfx: ['sparkle', 'soft-bell', 'bubble'],
    graphics: ['オーロラグラデ', '虹色ホログラム', 'ふわっとしたぼかし', '星・月モチーフ', '丸いフレーム'],
    gfx: ['mesh', 'bokeh'],
  },
  {
    id: 'neon', name: 'ネオン・サイバー', keywords: ['ゲーム', 'eスポーツ', 'ネオン', 'サイバーパンク', '夜'],
    palettes: [
      { name: 'Cyberpunk', bg: '#0A0014', surface: '#1A0633', text: '#F5F0FF', primary: '#00F0FF', accent: '#FF00A8' },
      { name: 'Toxic', bg: '#050A05', surface: '#0E1A0E', text: '#E8FFE8', primary: '#39FF14', accent: '#FFE600' },
      { name: 'Night City', bg: '#0B0B1E', surface: '#16163A', text: '#FFFFFF', primary: '#FF2079', accent: '#00E5FF' },
      { name: 'Ultraviolet', bg: '#07001A', surface: '#140033', text: '#F0E6FF', primary: '#B026FF', accent: '#00FFC6' },
    ],
    fonts: [
      { head: 'DotGothic16', body: 'Noto Sans JP', en: 'Orbitron' },
      { head: 'Dela Gothic One', body: 'Noto Sans JP', en: 'Audiowide' },
      { head: 'Noto Sans JP', body: 'Noto Sans JP', en: 'Rajdhani' },
    ],
    motions: ['glitch', 'neon-flicker', 'grid3d', 'scanline', 'typewriter', 'tilt-3d'],
    sfx: ['glitch', 'level-up', 'riser', 'unlock'],
    graphics: ['ネオン管風の発光文字', 'スキャンライン', 'HUD風の枠', '六角形パターン', 'RGBずれ'],
    gfx: ['grid3d', 'constellation'],
  },
  {
    id: 'handmade', name: 'ハンドメイド・手書き', keywords: ['手書き', 'あたたかい', 'イラスト', 'ほっこり', '地域'],
    palettes: [
      { name: 'Kraft', bg: '#F5EBDD', surface: '#EAD9C0', text: '#3A2B1E', primary: '#D1603D', accent: '#4A7C59' },
      { name: 'Crayon', bg: '#FFFDF7', surface: '#FFF1D6', text: '#2E2A24', primary: '#F4A259', accent: '#5B8E7D' },
      { name: 'Chalkboard', bg: '#2F3E35', surface: '#3B4D42', text: '#F4F1E8', primary: '#F6D365', accent: '#F79D84' },
      { name: 'Picnic', bg: '#FFF9F0', surface: '#FFE8CC', text: '#3B2F2F', primary: '#E07A5F', accent: '#81B29A' },
    ],
    fonts: [
      { head: 'Klee One', body: 'Zen Maru Gothic', en: 'Caveat' },
      { head: 'Yomogi', body: 'Zen Maru Gothic', en: 'Patrick Hand' },
      { head: 'Hachi Maru Pop', body: 'Kiwi Maru', en: 'Gochi Hand' },
    ],
    motions: ['line-draw', 'wiggle', 'float', 'stamp-in', 'pop', 'bounce'],
    sfx: ['pop', 'page-turn', 'bubble'],
    graphics: ['手書きの矢印・下線', 'マスキングテープ', 'クレヨン質感', 'イラストアイコン', 'スタンプ'],
    gfx: [null, 'sakura'],
  },
  {
    id: 'nordic', name: '北欧・ライフスタイル', keywords: ['北欧', '暮らし', 'インテリア', 'くすみカラー', '心地よい'],
    palettes: [
      { name: 'Fika', bg: '#F7F4EF', surface: '#E9E2D6', text: '#2E2B28', primary: '#6E8B8B', accent: '#D9A68E' },
      { name: 'Fjord', bg: '#F4F6F6', surface: '#E1E8E8', text: '#1F2A2E', primary: '#3D5A6C', accent: '#E3B23C' },
      { name: 'Birch', bg: '#FAF8F5', surface: '#EEE7DD', text: '#332E28', primary: '#9C6644', accent: '#7F9C96' },
      { name: 'Dusty Rose', bg: '#FAF5F3', surface: '#F1E3DE', text: '#3A2E2C', primary: '#C08B83', accent: '#6D8A7A' },
    ],
    fonts: [
      { head: 'Zen Kaku Gothic New', body: 'Noto Sans JP', en: 'Josefin Sans' },
      { head: 'Kaisei Decol', body: 'Noto Sans JP', en: 'Lora' },
      { head: 'Zen Maru Gothic', body: 'Noto Sans JP', en: 'Work Sans' },
    ],
    motions: ['fade-up', 'image-hover-zoom', 'parallax', 'clip-up', 'stagger', 'float'],
    sfx: ['soft-bell', 'tick', 'drop'],
    graphics: ['くすみカラーの面', '幾何学の小物', 'アーチ型の写真', '小さな英字ラベル', 'リネン質感'],
    gfx: [null, 'rings'],
  },
  {
    id: 'geometric', name: 'ジオメトリック・グラフィカル', keywords: ['幾何学', 'バウハウス', 'グラフィック', '図形', 'モダン'],
    palettes: [
      { name: 'Bauhaus', bg: '#F2EBDD', surface: '#FFFFFF', text: '#1B1B1B', primary: '#D7263D', accent: '#1B5299' },
      { name: 'Primary Shapes', bg: '#FFFFFF', surface: '#F6F6F6', text: '#121212', primary: '#FFC300', accent: '#0057FF' },
      { name: 'Memphis', bg: '#FFF4E6', surface: '#FFFFFF', text: '#1A1A1A', primary: '#FF5D8F', accent: '#00B2CA' },
      { name: 'Swiss', bg: '#FFFFFF', surface: '#EFEFEF', text: '#000000', primary: '#E30613', accent: '#000000' },
    ],
    fonts: [
      { head: 'Zen Kaku Gothic New', body: 'Noto Sans JP', en: 'Archivo' },
      { head: 'Noto Sans JP', body: 'Noto Sans JP', en: 'Unbounded' },
      { head: 'M PLUS 1p', body: 'Noto Sans JP', en: 'Lexend' },
    ],
    motions: ['shape-morph', 'rotate-in', 'stagger', 'spin', 'clip-circle', 'parallax'],
    sfx: ['pop', 'click', 'tick'],
    graphics: ['円・三角・四角の構成', 'グリッドシステム', '原色の面分割', '大きな数字', '線と点のパターン'],
    gfx: [null, 'rings'],
  },
  {
    id: 'clay3d', name: '3D・クレイ', keywords: ['3D', '立体', 'クレイ', 'ぷにぷに', 'アイコン'],
    palettes: [
      { name: 'Clay Peach', bg: '#FFF1E8', surface: '#FFFFFF', text: '#2D2A32', primary: '#FF8A65', accent: '#7E57C2' },
      { name: 'Clay Blue', bg: '#EAF2FF', surface: '#FFFFFF', text: '#1D2433', primary: '#4F7CFF', accent: '#FFB547' },
      { name: 'Clay Mint', bg: '#E9FBF4', surface: '#FFFFFF', text: '#1F2E2A', primary: '#2BB673', accent: '#FF6F91' },
      { name: 'Clay Lilac', bg: '#F3EEFF', surface: '#FFFFFF', text: '#28213A', primary: '#9B6BFF', accent: '#33D1B5' },
    ],
    fonts: [
      { head: 'M PLUS Rounded 1c', body: 'Noto Sans JP', en: 'Poppins' },
      { head: 'Zen Maru Gothic', body: 'Noto Sans JP', en: 'Nunito' },
      { head: 'Kiwi Maru', body: 'Noto Sans JP', en: 'Baloo 2' },
    ],
    motions: ['float', 'tilt-3d', 'squash-bounce', 'pop', 'parallax', 'magnetic'],
    sfx: ['pop', 'bubble', 'toggle', 'success'],
    graphics: ['インナーシャドウの立体ボタン', '3Dイラスト', 'ソフトな影', 'ぷっくりアイコン', '丸角の大きなカード'],
    gfx: ['bokeh', null],
  },
];

/** 業種（案件でよく来るもの） */
export const INDUSTRIES = [
  { id: 'beauty-salon', name: '美容室・ヘアサロン', styles: ['minimal', 'nordic', 'editorial', 'cute', 'luxury'], target: '20〜40代女性' },
  { id: 'esthe', name: 'エステ・脱毛サロン', styles: ['luxury', 'cute', 'pastel', 'minimal'], target: '20〜40代女性' },
  { id: 'cosme', name: 'コスメ・スキンケア', styles: ['minimal', 'luxury', 'pastel', 'natural', 'glass'], target: '20〜40代女性' },
  { id: 'clinic-beauty', name: '美容クリニック', styles: ['luxury', 'trust', 'minimal'], target: '25〜45歳女性' },
  { id: 'dental', name: '歯科医院', styles: ['trust', 'natural', 'minimal'], target: '地域の家族層' },
  { id: 'clinic', name: '内科・クリニック', styles: ['trust', 'natural', 'nordic'], target: '地域住民' },
  { id: 'cafe', name: 'カフェ・ベーカリー', styles: ['natural', 'nordic', 'handmade', 'retro', 'editorial'], target: '20〜40代' },
  { id: 'restaurant', name: 'レストラン・居酒屋', styles: ['wamodern', 'cinematic', 'retro', 'luxury'], target: '会社員・グループ' },
  { id: 'sweets', name: '和菓子・スイーツ', styles: ['wamodern', 'cute', 'pastel', 'natural'], target: 'ギフト需要・女性' },
  { id: 'ryokan', name: 'ホテル・旅館', styles: ['wamodern', 'luxury', 'cinematic', 'minimal'], target: 'カップル・ファミリー旅行者' },
  { id: 'tourism', name: '観光・地域プロモーション', styles: ['wamodern', 'natural', 'handmade', 'cinematic'], target: '国内外の旅行者' },
  { id: 'realestate', name: '不動産・マンション', styles: ['luxury', 'trust', 'minimal', 'cinematic'], target: '30〜50代の購入検討層' },
  { id: 'housing', name: '工務店・注文住宅・リフォーム', styles: ['natural', 'nordic', 'trust', 'minimal'], target: '子育て世帯' },
  { id: 'architect', name: '建築設計事務所', styles: ['minimal', 'editorial', 'geometric'], target: '施主・法人' },
  { id: 'gym', name: 'パーソナルジム・フィットネス', styles: ['sporty', 'cinematic', 'tech'], target: '20〜40代男女' },
  { id: 'yoga', name: 'ヨガ・ピラティス', styles: ['natural', 'pastel', 'minimal', 'nordic'], target: '20〜40代女性' },
  { id: 'saas', name: 'SaaS・BtoBツール', styles: ['tech', 'glass', 'trust', 'clay3d', 'minimal'], target: '企業の担当者・決裁者' },
  { id: 'ai', name: 'AIサービス・スタートアップ', styles: ['tech', 'glass', 'neon', 'minimal'], target: '経営者・エンジニア' },
  { id: 'app', name: 'スマホアプリ', styles: ['clay3d', 'glass', 'pop', 'tech'], target: '10〜30代' },
  { id: 'recruit', name: '採用・求人', styles: ['trust', 'editorial', 'sporty', 'pop', 'geometric'], target: '新卒・転職希望者' },
  { id: 'school', name: 'スクール・オンライン講座', styles: ['pop', 'trust', 'tech', 'clay3d'], target: '学び直しの社会人' },
  { id: 'programming', name: 'プログラミングスクール', styles: ['tech', 'neon', 'clay3d', 'pop'], target: '未経験〜転職希望者' },
  { id: 'english', name: '英会話・語学', styles: ['pop', 'geometric', 'trust', 'clay3d'], target: '社会人・学生' },
  { id: 'kids', name: '保育園・幼児教育・習い事', styles: ['handmade', 'pop', 'cute', 'natural'], target: '子育て中の保護者' },
  { id: 'ec-fashion', name: 'アパレル・ファッションEC', styles: ['editorial', 'minimal', 'brutal', 'retro'], target: '10〜30代' },
  { id: 'ec-food', name: '食品・産直EC', styles: ['natural', 'handmade', 'wamodern', 'pop'], target: '30〜60代' },
  { id: 'wedding', name: 'ウェディング・結婚相談所', styles: ['luxury', 'pastel', 'cute', 'minimal'], target: '20〜30代カップル' },
  { id: 'finance', name: '金融・保険・投資', styles: ['trust', 'minimal', 'tech'], target: '30〜60代' },
  { id: 'legal', name: '士業（税理士・弁護士・行政書士）', styles: ['trust', 'minimal', 'wamodern'], target: '中小企業経営者・個人' },
  { id: 'consulting', name: 'コンサル・コーチング', styles: ['minimal', 'trust', 'editorial', 'luxury'], target: '経営者・個人事業主' },
  { id: 'webagency', name: 'Web制作・デザイン事務所', styles: ['brutal', 'editorial', 'tech', 'geometric', 'cinematic'], target: '中小企業' },
  { id: 'music-event', name: '音楽・ライブ・イベント', styles: ['neon', 'cinematic', 'retro', 'brutal'], target: '10〜30代ファン' },
  { id: 'game', name: 'ゲーム・eスポーツ', styles: ['neon', 'cinematic', 'retro', 'sporty'], target: '10〜30代ゲーマー' },
  { id: 'youtuber', name: 'YouTuber・インフルエンサー', styles: ['pop', 'brutal', 'neon', 'cute'], target: 'チャンネル視聴者' },
  { id: 'pet', name: 'ペット・トリミング・動物病院', styles: ['cute', 'handmade', 'natural', 'clay3d'], target: 'ペットオーナー' },
  { id: 'car', name: '自動車・バイク', styles: ['cinematic', 'sporty', 'luxury', 'tech'], target: '30〜50代男性' },
  { id: 'agri', name: '農業・地方の生産者', styles: ['natural', 'handmade', 'wamodern'], target: '食にこだわる消費者' },
  { id: 'npo', name: 'NPO・地方自治体', styles: ['trust', 'handmade', 'natural', 'geometric'], target: '地域住民・支援者' },
  { id: 'fortune', name: '占い・スピリチュアル', styles: ['pastel', 'cinematic', 'luxury', 'wamodern'], target: '20〜40代女性' },
  { id: 'crowdfunding', name: 'クラウドファンディング・新商品', styles: ['cinematic', 'tech', 'natural', 'pop'], target: '新しもの好きの支援者' },
  { id: 'moving', name: '引越し・生活サービス', styles: ['pop', 'trust', 'clay3d'], target: '単身・家族' },
  { id: 'sauna', name: 'サウナ・温浴施設', styles: ['retro', 'wamodern', 'natural', 'brutal'], target: '20〜40代' },
];

/** モーション辞書：DBの motion 名 → 実装方法（shared/ の何を使うか） */
export const MOTIONS = {
  'fade-up': { impl: 'data-reveal="fade-up"', desc: '下から20〜40pxフェードイン。全ジャンルの基本' },
  'clip-up': { impl: 'data-reveal="clip-up"', desc: '下から幕が上がるように出現。写真・見出しに' },
  'clip-left': { impl: 'data-reveal="clip-left"', desc: '左から右へ切り抜き出現。エディトリアル向け' },
  'clip-circle': { impl: 'data-reveal="clip-circle"', desc: '円形に広がって出現' },
  'mask-wipe': { impl: 'data-reveal="mask-wipe"', desc: '色帯が通過して中身が現れる。高級感' },
  'split-text': { impl: 'data-split="chars" data-reveal', desc: '1文字ずつ下から出る見出し（キネティックタイポ）' },
  'blur-in': { impl: 'data-reveal="blur-in"', desc: 'ぼかしから焦点が合う。上品・映画的' },
  'zoom-in': { impl: 'data-reveal="zoom-in"', desc: '縮小状態から拡大して出現' },
  'rotate-in': { impl: 'data-reveal="rotate-in"', desc: '少し傾いて出現。遊び心' },
  'pop': { impl: 'data-reveal="pop"', desc: '弾むように出現（バックイージング）' },
  'stagger': { impl: 'data-stagger="80"', desc: 'カード等を順番に出す' },
  'parallax': { impl: 'data-parallax="0.15"', desc: 'スクロール視差。奥行き表現' },
  'counter-up': { impl: 'data-counter="1200"', desc: '実績数字のカウントアップ' },
  'typewriter': { impl: 'data-typewriter data-sfx-type', desc: 'タイプ表示＋打鍵音' },
  'line-draw': { impl: 'data-line-draw（SVG）', desc: 'SVGの線が描かれていく' },
  'marquee': { impl: 'data-marquee="40"', desc: '無限に流れるテキスト帯' },
  'magnetic': { impl: 'data-magnetic', desc: 'ボタンがカーソルに吸い付く' },
  'tilt-3d': { impl: 'data-tilt', desc: 'カードが3Dに傾く＋光沢' },
  'cursor-follow': { impl: '<body data-cursor>', desc: 'カスタムカーソル（PCのみ）' },
  'scroll-progress': { impl: '<div data-scroll-progress>', desc: '読了進捗バー' },
  'sticky-scrub': { impl: 'section[data-pin] + CSS var(--p)', desc: 'スクロールに合わせて固定画面の中身が変化' },
  'horizontal-scroll': { impl: 'data-hscroll + data-hscroll-track', desc: '縦スクロールで横に流れるギャラリー' },
  'image-hover-zoom': { impl: 'CSS: img{transition:transform .8s} a:hover img{transform:scale(1.06)}', desc: '画像ホバーでゆっくり拡大' },
  'ken-burns': { impl: 'class="m-kenburns"', desc: '写真がゆっくりズーム&パン' },
  'shine-sweep': { impl: 'class="m-shine"', desc: '光が斜めに走る（CTA・ゴールド）' },
  'chrome-shine': { impl: 'class="m-shine" + メタリックグラデ', desc: 'クローム文字の反射' },
  'float': { impl: 'class="m-float"', desc: 'ふわふわ浮遊ループ' },
  'bounce': { impl: 'class="m-bounce"', desc: '跳ねるループ（矢印・バッジ）' },
  'wiggle': { impl: 'class="m-wiggle"', desc: '定期的にぷるっと揺れて注目を集める' },
  'spin': { impl: 'class="m-spin"', desc: '回転ループ（円形テキストバッジ）' },
  'pulse': { impl: 'class="m-pulse"', desc: 'CTAの波紋パルス' },
  'gradient-shift': { impl: 'class="m-gradient-shift"', desc: 'グラデーションがゆっくり流れる' },
  'blob-morph': { impl: 'class="m-blob"', desc: '有機的な形が変形し続ける' },
  'glitch': { impl: 'class="m-glitch" data-text="..."', desc: 'RGBずれのグリッチ' },
  'grain': { impl: 'class="m-grain"（position:relative要素に）', desc: 'フィルムノイズ' },
  'confetti': { impl: 'Motion.confetti()', desc: '紙吹雪（送信完了・当選）' },
  'ripple': { impl: 'data-ripple', desc: 'クリック波紋（マテリアル）' },
  'mesh': { impl: '<canvas data-gfx="mesh">', desc: '動くメッシュグラデーション背景' },
  'particles': { impl: '<canvas data-gfx="particles">', desc: '漂う粒子' },
  'constellation': { impl: '<canvas data-gfx="constellation">', desc: '線で繋がるネットワーク（AI/テック）' },
  'wave': { impl: '<canvas data-gfx="waves">', desc: '重なる波' },
  'grid3d': { impl: '<canvas data-gfx="grid3d">', desc: 'シンセウェーブの3Dグリッド' },
  'sakura': { impl: '<canvas data-gfx="sakura">', desc: '舞い散る花びら' },
  'sparkle': { impl: 'class="m-float" + ✦ 装飾 + SFX sparkle', desc: 'キラキラ演出' },
  'heart-burst': { impl: 'Motion.confetti({colors:[ピンク系]})', desc: 'ハートが弾ける' },
  'glow-border': { impl: 'conic-gradient の回転ボーダー', desc: '光が周回する枠線' },
  'skew-reveal': { impl: 'transform: skewY(6deg) → 0', desc: '斜めから立ち上がる（スポーツ）' },
  'speed-lines': { impl: 'repeating-linear-gradient の流れる線', desc: 'スピード線' },
  'impact-shake': { impl: '@keyframes shake + SFX impact', desc: '着地の揺れ' },
  'letterbox-open': { impl: '上下の黒帯が開く clip-path', desc: '映画のオープニング' },
  'vertical-text-reveal': { impl: 'writing-mode: vertical-rl + clip-up', desc: '縦書きが上から現れる' },
  'ink-spread': { impl: 'clip-path circle + feTurbulence フィルタ', desc: '墨が滲むように出現' },
  'neon-flicker': { impl: '@keyframes flicker（opacity不規則）', desc: 'ネオン管の点滅' },
  'scanline': { impl: 'repeating-linear-gradient オーバーレイ', desc: 'ブラウン管の走査線' },
  'hard-shadow-press': { impl: 'box-shadow 6px 6px 0 → 0 + translate', desc: '押し込めるブルータルボタン' },
  'stamp-in': { impl: 'scale(2)→1 + rotate + SFX pop', desc: 'ハンコを押す演出' },
  'shape-morph': { impl: 'border-radius / clip-path の遷移', desc: '図形が変形' },
  'squash-bounce': { impl: 'scaleY .8→1.1→1', desc: 'ぷにっと弾む（クレイ）' },
};

/** 効果音辞書：shared/js/sfx.js のプリセット名と使いどころ */
export const SFX = {
  click: 'ボタン押下（硬め・テック）', tick: 'ホバー・タブ切替（控えめ）', hover: 'カードホバー', pop: '要素の出現・追加',
  bubble: 'いいね・リアクション（柔らかい）', toggle: 'スイッチON', 'toggle-off': 'スイッチOFF', whoosh: 'スライド遷移・画面切替',
  swoosh: 'メニュー開閉', swipe: 'カードスワイプ', success: '送信完了・購入完了', chime: 'お知らせ・上品な完了',
  notify: '通知バッジ', error: 'エラー・入力ミス', coin: 'ポイント獲得・クーポン', sparkle: 'キラキラ演出・当選',
  drop: '水滴・ナチュラル', typing: 'タイプライター打鍵', impact: 'ロゴ着地・ドン！', riser: '期待感の盛り上げ（OP）',
  glitch: 'グリッチ演出', 'page-turn': 'ページめくり・記事遷移', shutter: '写真・ギャラリー', confetti: '紙吹雪とセット',
  unlock: 'ロック解除・プレミアム開放', 'level-up': '達成・ランクアップ', heartbeat: '緊張感・医療', 'soft-bell': '上品な合図（高級・和）',
  koto: '和の演出（琴風）', jingle: 'ロゴ表示・ローディング完了',
};

export const ACCESSIBILITY = [
  '本文と背景のコントラスト比 4.5:1 以上（大見出しは 3:1 以上）',
  'タップ領域は 44×44px 以上',
  'prefers-reduced-motion で動きを停止（shared/css/motion.css で自動対応）',
  '効果音には必ずON/OFFボタンを付け、初期状態は控えめな音量に',
  '画像には意味のある alt、装飾画像は alt=""',
  '色だけで情報を伝えない（アイコン・テキストを併用）',
];
